<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExampleInfoRegistration.DAL\ExampleInfoRegistration.DAL.csproj" />
    <ProjectReference Include="..\ExampleInfoRegistration.Entities\ExampleInfoRegistration.Entities.csproj" />
  </ItemGroup>

</Project>
